/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agi.billpayment;

import java.io.File;  // Import the File class
import java.io.FileWriter;   // Import the FileWriter class
import java.io.IOException;  // Import the IOException class to handle errors
/**
 *
 * @author Agi
 */
public class BillDetail extends javax.swing.JFrame {

    /**
     * Creates new form BillDetail
     */
    private Home home;
    private User user;
    
    private String paymentMethod;
    public BillDetail(Home home, User user, String paymentMethod) {
        this.home = home;
        this.user = user;
        this.paymentMethod = paymentMethod;
        
        initComponents();
        
        Start();
    }
    private void Start() {
        try {
            jLabelNamaPelangganInfo.setText(user.nama);
            jLabelNamaProdukInfo.setText(user.listTagihan.get(0).product.nama);
            jLabelCodeInfo.setText(user.listTagihan.get(0).kode);
            jLabelTotalTagihanInfo.setText(String.valueOf(user.listTagihan.get(0).total));
            jLabelPaymentMethodInfo.setText(paymentMethod);
        } catch (NullPointerException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabelNamaPelanggan = new javax.swing.JLabel();
        jLabelNamaProduk = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonContinue = new javax.swing.JButton();
        jLabelCode = new javax.swing.JLabel();
        jLabelTotalTagihan = new javax.swing.JLabel();
        jLabelPaymentMethod = new javax.swing.JLabel();
        jLabelNamaPelangganInfo = new javax.swing.JLabel();
        jLabelNamaProdukInfo = new javax.swing.JLabel();
        jLabelCodeInfo = new javax.swing.JLabel();
        jLabelPaymentMethodInfo = new javax.swing.JLabel();
        jLabelTotalTagihanInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1031, 500));
        setPreferredSize(new java.awt.Dimension(1031, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        logo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logo.setText("Tagihan Anda");

        jLabelNamaPelanggan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelNamaPelanggan.setText("Nama pelanggan     :");

        jLabelNamaProduk.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelNamaProduk.setText("Nama produk          :");

        jButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorder(null);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonContinue.setBackground(new java.awt.Color(94, 163, 91));
        jButtonContinue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonContinue.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContinue.setText("Lanjutkan");
        jButtonContinue.setBorder(null);
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        jLabelCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelCode.setText("Kode                     :");

        jLabelTotalTagihan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelTotalTagihan.setText("Total tagihan           :");

        jLabelPaymentMethod.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelPaymentMethod.setText("Metode pembayaran :");

        jLabelNamaPelangganInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelNamaPelangganInfo.setText("Nama pelanggan");

        jLabelNamaProdukInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelNamaProdukInfo.setText("Nama produk");

        jLabelCodeInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelCodeInfo.setText("Kode");

        jLabelPaymentMethodInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelPaymentMethodInfo.setText("Metode pembayaran");

        jLabelTotalTagihanInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelTotalTagihanInfo.setText("Total tagihan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 384, Short.MAX_VALUE)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNamaPelanggan)
                                    .addComponent(jLabelNamaProduk)
                                    .addComponent(jLabelCode)
                                    .addComponent(jLabelTotalTagihan)
                                    .addComponent(jLabelPaymentMethod))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPaymentMethodInfo)
                                    .addComponent(jLabelCodeInfo)
                                    .addComponent(jLabelNamaProdukInfo)
                                    .addComponent(jLabelNamaPelangganInfo)
                                    .addComponent(jLabelTotalTagihanInfo))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaPelanggan)
                    .addComponent(jLabelNamaPelangganInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaProduk)
                    .addComponent(jLabelNamaProdukInfo))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCode)
                    .addComponent(jLabelCodeInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalTagihan)
                    .addComponent(jLabelTotalTagihanInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaymentMethod)
                    .addComponent(jLabelPaymentMethodInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        
        
            jLabelNamaPelangganInfo.setText(user.nama);
            jLabelNamaProdukInfo.setText(user.listTagihan.get(0).product.nama);
            jLabelCodeInfo.setText(user.listTagihan.get(0).kode);
            jLabelTotalTagihanInfo.setText(String.valueOf(user.listTagihan.get(0).total));
            jLabelPaymentMethodInfo.setText(paymentMethod);
        try {
            File file = new File("Struk.txt");
            if (file.createNewFile()) {
              System.out.println("File created: " + file.getName());
            } else {
                try { 
                    FileWriter fileWriter = new FileWriter("Struk.txt");
                    fileWriter.write(""
                            + "Nama pelanggan   : " + user.nama + "\n"
                            + "Nama Produk      : " + user.listTagihan.get(0).product.nama + "\n"
                            + "Kode             : " + user.listTagihan.get(0).kode + "\n"
                            + "Tagihan          : " + String.valueOf(user.listTagihan.get(0).total) + "\n"
                            + "Metode Pembayaran: " + paymentMethod);
                    fileWriter.close();
                } catch (IOException e) {
                    System.out.println("An error occurred.");
                    e.printStackTrace();
                }
            }
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetail().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelCodeInfo;
    private javax.swing.JLabel jLabelNamaPelanggan;
    private javax.swing.JLabel jLabelNamaPelangganInfo;
    private javax.swing.JLabel jLabelNamaProduk;
    private javax.swing.JLabel jLabelNamaProdukInfo;
    private javax.swing.JLabel jLabelPaymentMethod;
    private javax.swing.JLabel jLabelPaymentMethodInfo;
    private javax.swing.JLabel jLabelTotalTagihan;
    private javax.swing.JLabel jLabelTotalTagihanInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
