/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agi.billpayment;

import com.agi.billpayment.BillManagement;
import com.agi.billpayment.Product;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Agi
 */

public class Home extends javax.swing.JFrame{

    /**
     * Variables
     */ 
    private BillManagement bill; 
    private List<javax.swing.JButton> JButtonsSearchList;
    private List<javax.swing.JButton> JButtonsRekomList;
    private List<Product> searchResults; 
    
    private Product product;
    
    public Home() {
        initAwake();
        initComponents();
        initStart();
    }
    
    private void initAwake() {   
        bill = new BillManagement(10);
        JButtonsRekomList = new ArrayList<>(); 
    }                 
    private void initStart() { 
        //list button rekom
        JButtonsRekomList.add(jButtonRekom0);
        JButtonsRekomList.add(jButtonRekom1);
        JButtonsRekomList.add(jButtonRekom2);
        JButtonsRekomList.add(jButtonRekom3);
        JButtonsRekomList.add(jButtonRekom4);
        JButtonsRekomList.add(jButtonRekom5);
        
        /*
        jButton = new javax.swing.JButton();
        jButton.setBackground(new java.awt.Color(248, 248, 248));
        jButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton.setForeground(new java.awt.Color(14, 15, 16));
        jButton.setText("Marketpedia");
        jButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        
        
        javax.swing.GroupLayout jPanelRekomListLayout = new javax.swing.GroupLayout(jPanelRekomList);
        jPanelRekomList.setLayout(jPanelRekomListLayout); 
        
        jPanelRekomListLayout.setHorizontalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRekomListLayout.setVerticalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        */
    }
    
    public BillManagement GetBill(){
        if(bill == null) return new BillManagement(10);
        return bill;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanelProduct = new javax.swing.JPanel();
        jPanelSearchResult = new javax.swing.JPanel();
        jPanelRekomList = new javax.swing.JPanel();
        jButtonRekom0 = new javax.swing.JButton();
        jButtonRekom1 = new javax.swing.JButton();
        jButtonRekom2 = new javax.swing.JButton();
        jButtonRekom3 = new javax.swing.JButton();
        jButtonRekom4 = new javax.swing.JButton();
        jButtonRekom5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1031, 500));
        setResizable(false);

        jPanelLogo.setBackground(new java.awt.Color(251, 251, 251));

        logo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logo.setText("Tagihan Anda");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanelSearch.setBackground(new java.awt.Color(251, 251, 251));

        jTextFieldSearch.setToolTipText("");
        jTextFieldSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 4, true));
        jTextFieldSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldSearch.setMaximumSize(new java.awt.Dimension(10, 30));
        jTextFieldSearch.setName(""); // NOI18N
        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(10, 22));
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanelProduct.setBackground(new java.awt.Color(251, 251, 251));

        jPanelSearchResult.setBackground(new java.awt.Color(251, 251, 251));

        javax.swing.GroupLayout jPanelSearchResultLayout = new javax.swing.GroupLayout(jPanelSearchResult);
        jPanelSearchResult.setLayout(jPanelSearchResultLayout);
        jPanelSearchResultLayout.setHorizontalGroup(
            jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSearchResultLayout.setVerticalGroup(
            jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelRekomList.setBackground(new java.awt.Color(251, 251, 251));

        jButtonRekom0.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom0.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom0.setText("Marketpedia");
        jButtonRekom0.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRekom0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom0ActionPerformed(evt);
            }
        });

        jButtonRekom1.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom1.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom1.setText("Bukatoko");
        jButtonRekom1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom1ActionPerformed(evt);
            }
        });

        jButtonRekom2.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom2.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom2.setText("Speedy");
        jButtonRekom2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom2ActionPerformed(evt);
            }
        });

        jButtonRekom3.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom3.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom3.setText("PDAM");
        jButtonRekom3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom3ActionPerformed(evt);
            }
        });

        jButtonRekom4.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom4.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom4.setText("Pulsa");
        jButtonRekom4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom4ActionPerformed(evt);
            }
        });

        jButtonRekom5.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom5.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom5.setText("Paketan");
        jButtonRekom5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRekomListLayout = new javax.swing.GroupLayout(jPanelRekomList);
        jPanelRekomList.setLayout(jPanelRekomListLayout);
        jPanelRekomListLayout.setHorizontalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRekom0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelRekomListLayout.setVerticalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRekom0, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRekomList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearchResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanelRekomList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        if(JButtonsSearchList == null) JButtonsSearchList = new ArrayList<>();
        
        //visible the logo
        jPanelLogo.setVisible(false);

        //visible the rekoms
        for(javax.swing.JButton button : JButtonsRekomList){
            button.setVisible(false); 
        }
        
        //reset  
        jPanelSearchResult.removeAll();
        JButtonsSearchList.removeAll(JButtonsSearchList); 
        
        // ketika menulis 
        if(jTextFieldSearch.getText().length() > 0){  
            searchResults = bill.SearchProducts(jTextFieldSearch.getText()); 
            
            for (Product product : searchResults) {
                System.out.print(product.nama + " ");
            }
            System.out.println();
            
            if(searchResults.size() >= 1){ 
                jPanelSearchResult.setVisible(true);
                
                for (Product product : searchResults ) { 
                    if(JButtonsSearchList.size() < 3){
                        javax.swing.JButton buttonResult = new javax.swing.JButton();
                        JButtonsSearchList.add(buttonResult); 
                        System.out.print(JButtonsSearchList.indexOf(buttonResult) + " ");

                        buttonResult.setBackground(new java.awt.Color(248, 248, 248));
                        buttonResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                        buttonResult.setForeground(new java.awt.Color(14, 15, 16));

                        buttonResult.setText(product.nama);

                        buttonResult.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                        buttonResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                        buttonResult.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                                ButtonResultActionPerformed(evt);
                        }});
                    } else break;
                    
                }
                System.out.println();
                javax.swing.GroupLayout jPanelSearchResultLayout = new javax.swing.GroupLayout(jPanelSearchResult);
                jPanelSearchResult.setLayout(jPanelSearchResultLayout);
                System.out.println("Ditemukan : " + JButtonsSearchList.size());
                try {
                    switch(JButtonsSearchList.size()){
                        case 1: 
                            jPanelSearchResultLayout.setHorizontalGroup(
                                jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchResultLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JButtonsSearchList.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                );
                            jPanelSearchResultLayout.setVerticalGroup(
                                jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSearchResultLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JButtonsSearchList.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            );
                        case 2: 
                            jPanelSearchResultLayout.setHorizontalGroup(
                                jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchResultLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JButtonsSearchList.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonsSearchList.get(1), javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                );
                            jPanelSearchResultLayout.setVerticalGroup(
                                jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSearchResultLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JButtonsSearchList.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonsSearchList.get(1), javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            );
                        case 3:
                            jPanelSearchResultLayout.setHorizontalGroup(
                                jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchResultLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JButtonsSearchList.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonsSearchList.get(1), javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonsSearchList.get(2), javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                );
                            jPanelSearchResultLayout.setVerticalGroup(
                                jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSearchResultLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JButtonsSearchList.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonsSearchList.get(1), javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonsSearchList.get(2), javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            ); 
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                } 
            }else{ 
                try { 
                    jPanelSearchResult.removeAll();
                    jPanelSearchResult.setVisible(false);
                    searchResults.removeAll(searchResults); 
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                } 
            }
        }else{
            jPanelLogo.setVisible(true);  

            for(javax.swing.JButton button : JButtonsRekomList){
                button.setVisible(true);
            } 
            try { 
                jPanelSearchResult.removeAll();
                searchResults.removeAll(searchResults); 
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } 
        }
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButtonRekom0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom0ActionPerformed
        product = bill.GetProductInformation("Marketpedia");
         
        ProductPicker();
    }//GEN-LAST:event_jButtonRekom0ActionPerformed

    private void jButtonRekom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom1ActionPerformed
        product = bill.GetProductInformation("Bukatoko");
         
        ProductPicker();
    }//GEN-LAST:event_jButtonRekom1ActionPerformed

    private void jButtonRekom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom2ActionPerformed
        product = bill.GetProductInformation("Speedy");
         
        ProductPicker();
    }//GEN-LAST:event_jButtonRekom2ActionPerformed

    private void jButtonRekom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom3ActionPerformed
        product = bill.GetProductInformation("PDAM");
         
        ProductPicker();
    }//GEN-LAST:event_jButtonRekom3ActionPerformed

    private void jButtonRekom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom4ActionPerformed
        product = bill.GetProductInformation("Pulsa");
         
        ProductPicker();
    }//GEN-LAST:event_jButtonRekom4ActionPerformed

    private void jButtonRekom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom5ActionPerformed
        product = bill.GetProductInformation("Paketan");
         
        ProductPicker();
    }//GEN-LAST:event_jButtonRekom5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < bill.userList.size(); i++) {
            System.out.println(bill.userList.get(i).nama);
            for (int j = 0; j < bill.userList.get(i).listTagihan.size(); j++) {
                System.out.print(bill.userList.get(i).listTagihan.get(j).product.nama + " ");
                System.out.println(bill.userList.get(i).listTagihan.get(j).total);
                System.out.println(bill.userList.get(i).listTagihan.get(j).kode);
            }
            System.out.println("");
        }
        
        for (int i = 0; i < bill.productsList.size(); i++) {
                System.out.println(bill.productsList.get(i).nama);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        
    
    private void ButtonResultActionPerformed(java.awt.event.ActionEvent evt){
        String productName = ((javax.swing.JButton)evt.getSource()).getText();
        product = bill.GetProductInformation(productName);
         
        ProductPicker();
    }
    
    private void ProductPicker(){ 
        InputCodeFrame inputCodeFrame = new InputCodeFrame(product, this);
        
        //dispose();
        inputCodeFrame.setVisible(true);
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRekom0;
    private javax.swing.JButton jButtonRekom1;
    private javax.swing.JButton jButtonRekom2;
    private javax.swing.JButton jButtonRekom3;
    private javax.swing.JButton jButtonRekom4;
    private javax.swing.JButton jButtonRekom5;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JPanel jPanelRekomList;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelSearchResult;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
 
}
