/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agi;
   
import java.util.*;
import com.agi.billpayment.BillManagement;
import com.agi.billpayment.Product;

/**
 *
 * @author Agi
 */

public class Home extends javax.swing.JFrame {

    /**
     * initializations Variables
     */
    
    private BillManagement bill;
    private List<javax.swing.JButton> JButtonsSearchList;
    private List<javax.swing.JButton> JButtonsRekomList;
    private List<Product> searchResults;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initAwake();
        initComponents();
        initStart();
    }
    
    private void initAwake() {  
        bill = new BillManagement(10); 
    }                 
    private void initStart() { 
        //list button rekom
        JButtonsRekomList = new ArrayList<>();
        JButtonsRekomList.add(jButtonRekom0);
        JButtonsRekomList.add(jButtonRekom1);
        JButtonsRekomList.add(jButtonRekom2);
        JButtonsRekomList.add(jButtonRekom3);
        JButtonsRekomList.add(jButtonRekom4);
        JButtonsRekomList.add(jButtonRekom5); 
        
        /*
        jButton = new javax.swing.JButton();
        jButton.setBackground(new java.awt.Color(248, 248, 248));
        jButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton.setForeground(new java.awt.Color(14, 15, 16));
        jButton.setText("Marketpedia");
        jButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        
        
        javax.swing.GroupLayout jPanelRekomListLayout = new javax.swing.GroupLayout(jPanelRekomList);
        jPanelRekomList.setLayout(jPanelRekomListLayout); 
        
        jPanelRekomListLayout.setHorizontalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRekomListLayout.setVerticalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanelSearch = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanelProduct = new javax.swing.JPanel();
        jPanelRekomList = new javax.swing.JPanel();
        jButtonRekom0 = new javax.swing.JButton();
        jButtonRekom1 = new javax.swing.JButton();
        jButtonRekom2 = new javax.swing.JButton();
        jButtonRekom3 = new javax.swing.JButton();
        jButtonRekom4 = new javax.swing.JButton();
        jButtonRekom5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 217, 223));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanelLogo.setBackground(new java.awt.Color(214, 217, 223));

        logo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logo.setText("Tagihan Anda");

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanelSearch.setBackground(new java.awt.Color(214, 217, 223));

        jTextFieldSearch.setToolTipText("");
        jTextFieldSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 232, 232), 4, true));
        jTextFieldSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldSearch.setMaximumSize(new java.awt.Dimension(10, 30));
        jTextFieldSearch.setName(""); // NOI18N
        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(10, 22));
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanelProduct.setBackground(new java.awt.Color(214, 217, 223));

        jPanelRekomList.setBackground(new java.awt.Color(214, 217, 223));

        jButtonRekom0.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom0.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom0.setText("Marketpedia");
        jButtonRekom0.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRekom0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom0ActionPerformed(evt);
            }
        });

        jButtonRekom1.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom1.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom1.setText("Bukatoko");
        jButtonRekom1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom1ActionPerformed(evt);
            }
        });

        jButtonRekom2.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom2.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom2.setText("PLN");
        jButtonRekom2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom2ActionPerformed(evt);
            }
        });

        jButtonRekom3.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom3.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom3.setText("PDAM");
        jButtonRekom3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom3ActionPerformed(evt);
            }
        });

        jButtonRekom4.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom4.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom4.setText("Pulsa");
        jButtonRekom4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom4ActionPerformed(evt);
            }
        });

        jButtonRekom5.setBackground(new java.awt.Color(248, 248, 248));
        jButtonRekom5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRekom5.setForeground(new java.awt.Color(14, 15, 16));
        jButtonRekom5.setText("Paketan");
        jButtonRekom5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRekom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRekom5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRekomListLayout = new javax.swing.GroupLayout(jPanelRekomList);
        jPanelRekomList.setLayout(jPanelRekomListLayout);
        jPanelRekomListLayout.setHorizontalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRekom0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRekom5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRekomListLayout.setVerticalGroup(
            jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRekomListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRekom0, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRekom5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelProductLayout = new javax.swing.GroupLayout(jPanelProduct);
        jPanelProduct.setLayout(jPanelProductLayout);
        jPanelProductLayout.setHorizontalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRekomList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProductLayout.setVerticalGroup(
            jPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRekomList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProduct, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLogo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        if(jTextFieldSearch.getText().length() > 0){
            JButtonsSearchList = new ArrayList<>();
            System.out.println(jTextFieldSearch.getText());
            jPanelLogo.setVisible(false);
             
            for(javax.swing.JButton button : JButtonsRekomList){
                button.setVisible(false);
            }
            
            searchResults = bill.SearchProducts(jTextFieldSearch.getText());

            javax.swing.JPanel jPanelSearchResults = new javax.swing.JPanel();
            jPanelSearchResults.setBackground(new java.awt.Color(255, 255, 255));
            for (Product product : searchResults) {
                javax.swing.JButton buttonResult = new javax.swing.JButton();
                JButtonsSearchList.add(buttonResult);

                buttonResult.setBackground(new java.awt.Color(248, 248, 248));
                buttonResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                buttonResult.setForeground(new java.awt.Color(14, 15, 16));

                buttonResult.setText(product.nama);

                buttonResult.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                buttonResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                buttonResult.addActionListener((java.awt.event.ActionEvent evt1) -> {
                    ButtonResultActionPerformed(evt1);
                });
                
                javax.swing.GroupLayout jPanelRekomListLayout = new javax.swing.GroupLayout(jPanelRekomList);
                jPanelRekomList.setLayout(jPanelRekomListLayout); 

                jPanelRekomListLayout.setHorizontalGroup(
                    jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRekomListLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanelRekomListLayout.setVerticalGroup(
                    jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRekomListLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRekomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonResult, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );
            }
        }else{
            jPanelLogo.setVisible(true);
            
            for(javax.swing.JButton button : JButtonsRekomList){
                button.setVisible(true);
            }
            
            JButtonsSearchList.removeAll(JButtonsSearchList);
            for(javax.swing.JButton button : JButtonsSearchList){
                button.setVisible(false);
            }
            
            searchResults.removeAll(searchResults);
            
            System.out.println(searchResults);
        }
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButtonRekom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRekom5ActionPerformed

    private void jButtonRekom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRekom4ActionPerformed

    private void jButtonRekom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRekom3ActionPerformed

    private void jButtonRekom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRekom2ActionPerformed

    private void jButtonRekom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRekom1ActionPerformed

    private void jButtonRekom0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekom0ActionPerformed

    }//GEN-LAST:event_jButtonRekom0ActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    
    private void ButtonResultActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(JButtonsSearchList.size() <= 0) return;
        //check by searhlist text == search results name
        for (javax.swing.JButton button : JButtonsSearchList) {
            Object getButtonObj = evt.getSource();
            if(button.equals(getButtonObj)){
                System.out.println(button.getText());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRekom0;
    private javax.swing.JButton jButtonRekom1;
    private javax.swing.JButton jButtonRekom2;
    private javax.swing.JButton jButtonRekom3;
    private javax.swing.JButton jButtonRekom4;
    private javax.swing.JButton jButtonRekom5;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JPanel jPanelRekomList;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
 
}
